# https://confluence.seges.dk/pages/viewpage.action?pageId=166958870
name: 'jsonvariables'
description: 'Manage all variables in a json file. Substitute variables based on environment scope and set as environment variables'
inputs:
  ConfigFile:  # configuration filename
    description: 'full path and filename of the configuration file'
    required: true
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: "composite"
  steps:
    - run: |
        Import-Module ${{ github.action_path }}/src/Set-JsonVariables.psm1 -Force
        # ${{ github.action_path }}/client.ps1 -IdentityServerClientId ${{ inputs.IdentityServerClientId }} -IdentityServerClientSecret '${{ inputs.IdentityServerClientSecret }}' -IdentityServerUrl '${{ inputs.IdentityServerUrl  }}' -ResourceEnvironment '${{ inputs.ResourceEnvironment }}' -ClientId '${{ inputs.ClientId }}' -ClientName '${{ inputs.ClientName }}' -AllowedScopes '${{ inputs.AllowedScopes }}' -AllowedGrantTypes '${{ inputs.AllowedGrantTypes }}' -RedirectUris '${{ inputs.RedirectUris }}' -PostLogoutRedirectUri '${{ inputs.PostLogoutRedirectUri }}' -RequirePkce $requirePkceParsed -AllowOfflineAccess $allowOfflineAccessParsed -AllowedCorsOrigins '${{ inputs.AllowedCorsOrigins }}' -RoleFilter '${{ inputs.RoleFilter }}' 
      shell: pwsh