name: 'jsonvariables'
description: 'Manage all variables in a json file. Substitute variables based on environment scope and set as environment variables'
inputs:
  configFile:  # configuration filename
    description: 'full path and filename of the configuration file or just the filename'
    required: true
  scope:  # current scope to render the variables for
    description: 'Current scope - e.g. Dev, DevTest etc.'
    required: true
  secrets:  # all secrets as json
    description: 'All the secrets serialized as json'
    required: true
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: "composite"
  steps:
    - run: |
        ./src/Set-JsonVariables.ps1 -scope ${{inputs.scope}} -configFile ${{inputs.configFile}} -secrets ${{inputs.secrets}}
      shell: pwsh
    - name: Add config file as artifact
      uses: actions/upload-artifact@v2
      with:
        path: "./secrets.log"    