name: action-test
  
on: [push, workflow_dispatch]

jobs:
  test-action-minimal-linux:
    runs-on: ubuntu-latest
    environment: Dev
    steps:
    - uses: actions/checkout@v2

    - name: Set environment specific variables
      uses: jnus/json-variables@main
      with:
        scope: Dev
        configFile: 'variables.minimal.json'
    
    - name: print
      run: env

    - name: assert
      shell: pwsh
      run: |
        gci
        gci test
        $here = Split-Path $MyInvocation.MyCommand.Definition
        $path = Join-Path -Path ./ -ChildPath 'test'
        $module = Join-Path -Path $path -ChildPath 'Assertion.psm1'
        Import-Module $module -Force
        Assert-String -actual ${{env.Url}} -expected 'https://someDevHostName.com'