name: action-test
  
on: [push, workflow_dispatch]

jobs:
  test-action-minimal-linux:
    runs-on: ubuntu-latest
    environment: Dev
    steps:
    - uses: actions/checkout@v2

    - name: Set environment specific variables
      uses: jnus/json-variables@main
      with:
        scope: Dev
        configFile: 'variables.minimal.json'
    
    - name: print
      run: env

    - name: assert
      run: Write-host "assert"
      shell: pwsh