name: action-test
  
on: [push, workflow_dispatch]

jobs:
  test-action-minimal-dev:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    environment: Dev
    steps:
    - uses: actions/checkout@v2

    - name: Set environment specific variables
      uses: jnus/json-variables@support-substitution-of-secrets
      with:
        scope: Dev
        configFile: 'variables.minimal.json'
        secrets: '${{ toJson(secrets) }}'
    
    - name: print
      run: env

    - name: assert
      shell: pwsh
      run: |
        $here = Split-Path $MyInvocation.MyCommand.Definition
        $path = Join-Path -Path ./ -ChildPath 'test'
        $module = Join-Path -Path $path -ChildPath 'Assertion.psm1'
        Import-Module $module -Force
        Assert-EnvVar -actual ${{env.Url}} -expected 'https://someDevHostName.com' -envVar "env.Url"
        Assert-EnvVar -actual ${{env.HostName}} -expected 'someDevHostName' -envVar "env.HostName"
  
  
  test-action-minimal-devtest:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    environment: DevTest
    steps:
    - uses: actions/checkout@v2

    - name: log secrets
      shell: pwsh
      run: |
        add-content 'secrets.log' '${{ toJson(secrets) }}'

    - name: Add config file as artifact
      uses: actions/upload-artifact@v2
      with:
        path: "secrets.log"

    - name: Set environment specific variables
      uses: jnus/json-variables@main
      with:
        scope: DevTest
        configFile: 'test/variables.minimal.json'
        secrets: '${{ toJson(secrets) }}'
    
    - name: print
      run: env

    - name: Add config file as artifact
      uses: actions/upload-artifact@v2
      with:
        path: "secrets.log"

    # - name: assert
    #   shell: pwsh
    #   run: |
    #     $here = Split-Path $MyInvocation.MyCommand.Definition
    #     $path = Join-Path -Path ./ -ChildPath 'test'
    #     $module = Join-Path -Path $path -ChildPath 'Assertion.psm1'
    #     Import-Module $module -Force
    #     Assert-EnvVar -actual '${{env.Url}}' -expected 'https://someDevTestHostName.com' -envVar "env.Url"
    #     Assert-EnvVar -actual '${{env.HostName}}' -expected 'someDevTestHostName' -envVar "env.HostName"
    #     Assert-EnvVar -actual '${{env.SecretA}}' -expected 'repo_secret_a' -envVar "env.SecretA"

      