name: CI
  
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Test
      shell: pwsh
      run: | 
        ./test/run.ps1