name: ci
  
on: [push, workflow_dispatch]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    environment: Dev
    steps:
    - uses: actions/checkout@v2

    - name: test
      shell: pwsh
      run: | 
        .\test\run.ps1
    
    - name: print
      run: env