name: CI
  
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    environment: Dev
    steps:
    - uses: actions/checkout@v2

    - name: test
      shell: pwsh
      run: | 
        gci
        gci ./src
        gci ./test
        gci $PSScriptRoot
        ./test/run.ps1
    
    - name: print
      run: env