name: action-test
  
on: [push, workflow_dispatch]

jobs:
  test-action-minimal-devtest:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    environment: DevTest
    steps:
    - uses: actions/checkout@v2

    # - name: Set environment specific variables
    #   uses: jnus/json-variables@main
    #   with:
    #     scope: DevTest
    #     configFile: 'test/variables.minimal.json'
    #     secrets: '${{ toJson(secrets) }}'
    

    - name: assert
      shell: pwsh
      run: |
        $json = '${{ toJson(secrets) }}'
        $secrets = $json | ConvertFrom-Json -AsHashtable 
        $secret = $secrets['REPO_SECRET_A']
        Write-Output "ThisIsASecret=$secret" >> $Env:GITHUB_ENV
        Write-Host "$($_.Name)=$($_.Value)"

    - name: print
      run: env


      